# Generated by Django 4.1.7 on 2023-03-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion_real',
        ),
    ]
