# Generated by Django 4.1.7 on 2023-03-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(blank=True, choices=[('Si', True), ('No', False)], max_length=10, null=True),
        ),
    ]
