# Generated by Django 4.1.7 on 2023-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_prestamo_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='num_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
