# Generated by Django 4.1.7 on 2023-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_ejemplar_num_paginas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplar',
            old_name='num_paginas',
            new_name='cantidad',
        ),
    ]
