# Generated by Django 4.1.7 on 2023-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_num_paginas_ejemplar_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
