# Generated by Django 4.1.7 on 2023-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_ejemplar_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='libros', verbose_name='Imagen de Portada'),
        ),
    ]
