# Generated by Django 4.1.7 on 2023-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_libro_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='comentarios',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha a devolver'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(verbose_name='Fecha Prestamo'),
        ),
    ]
