# Generated by Django 4.1.7 on 2023-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_ejemplar_comentarios_alter_prestamo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
