# Generated by Django 4.1.7 on 2023-06-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_libro_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ano_aquision',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
