# Generated by Django 4.1.7 on 2023-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_libro_ano_aquision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='ano_aquision',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='ano_aquision',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
