# Generated by Django 4.1.7 on 2023-06-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_remove_libro_ano_aquision_ejemplar_ano_aquision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='edicion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='asignatura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='año_publicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='cutter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='dewey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='editorial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profesor_guia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
