# Generated by Django 4.1.7 on 2023-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_remove_libro_edicion_remove_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='ano_aquision',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año adquision'),
        ),
    ]
