# Generated by Django 4.1.7 on 2023-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_ejemplar_ano_aquision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
