# Generated by Django 4.1.7 on 2023-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_libro_sinopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
