# Generated by Django 4.1.7 on 2023-06-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_libro_isbn_ejemplar_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='ejemplar',
            name='fecha_adquisicion',
        ),
    ]
